export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const USER_UPDATED = "USER_UPDATED";
export const USER_DELETED= "USER_DELETED";
export const LOAD_3D = "LOAD_3D";
export const SET_USER_COUNT = "SET_USER_COUNT"; 

export const CLEAR_FILTER = "CLEAR_FILTER";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_TAG = "GET_TAG";
export const GET_TAG_INFO = "GET_TAG_INFO";
export const GET_TAGS = "GET_TAGS";
export const ADD_TAG = "ADD_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const SET_CURRENT_TAG = "SET_CURRENT_TAG";
export const CLEAR_TAG = "CLEAR_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const TAG_ERROR = "TAG_ERROR";
export const FILTER_TAG = "FILTER_TAG";
export const ADDING_TAG = "ADDING_TAG"

export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_FAV_EMPLOYEES = "GET_FAV_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEE_ERROR = "EMPLOYEE_ERROR";
export const FILTER_EMPLOYEE = "FILTER_EMPLOYEE";

export const GET_ASSET = "GET_ASSET";
export const GET_ASSETS = "GET_ASSETS";
export const GET_FAV_ASSETS = "GET_FAV_ASSETS";
export const ADD_ASSET = "ADD_ASSET";
export const UPDATE_ASSET = "UPDATE_ASSET";
export const SET_CURRENT_ASSET = "SET_CURRENT_ASSET";
export const CLEAR_ASSET = "CLEAR_ASSET";
export const DELETE_ASSET = "DELETE_ASSET";
export const ASSET_ERROR = "ASSET_ERROR";
export const FILTER_ASSET = "FILTER_ASSET";

export const GET_ANCHOR = "GET_ANCHOR";
export const GET_ANCHORS = "GET_ANCHORS";
export const GET_FAV_ANCHORS = "GET_FAV_ANCHORS";
export const ADD_ANCHOR = "ADD_ANCHOR";
export const UPDATE_ANCHOR = "UPDATE_ANCHOR";
export const SET_CURRENT_ANCHOR = "SET_CURRENT_ANCHOR";
export const CLEAR_ANCHOR = "CLEAR_ANCHOR";
export const DELETE_ANCHOR = "DELETE_ANCHOR";
export const ANCHOR_ERROR = "ANCHOR_ERROR";
export const FILTER_ANCHOR = "FILTER_ANCHOR";

export const GET_BUILDING = "GET_BUILDING";
export const GET_BUILDINGS = "GET_BUILDINGS";
export const GET_FAV_BUILDINGS = "GET_FAV_BUILDINGS";
export const ADD_BUILDING = "ADD_BUILDING";
export const UPDATE_BUILDING = "UPDATE_BUILDING";
export const SET_CURRENT_BUILDING = "SET_CURRENT_BUILDING";
export const CLEAR_BUILDING = "CLEAR_BUILDING";
export const DELETE_BUILDING = "DELETE_BUILDING";
export const BUILDING_ERROR = "BUILDING_ERROR";
export const FILTER_BUILDING = "FILTER_BUILDING";
export const SET_BUILDING_INDEX = "SET_BUILDING_INDEX";


export const GET_FLOORPLAN = "GET_FLOORPLAN";
export const GET_FLOORPLANS = "GET_FLOORPLANS";
export const GET_FAV_FLOORPLANS = "GET_FAV_FLOORPLANS";
export const ADD_FLOORPLAN = "ADD_FLOORPLAN";
export const UPDATE_FLOORPLAN = "UPDATE_FLOORPLAN";
export const SET_CURRENT_FLOORPLAN = "SET_CURRENT_FLOORPLAN";
export const CLEAR_FLOORPLAN = "CLEAR_FLOORPLAN";
export const DELETE_FLOORPLAN = "DELETE_FLOORPLAN";
export const FLOORPLAN_ERROR = "FLOORPLAN_ERROR";
export const FILTER_FLOORPLAN = "FILTER_FLOORPLAN";
export const SET_FLOORPLAN_INDEX = "SET_FLOORPLAN_INDEX";
export const GET_BUILDING_FLOORPLANS = "GET_BUILDING_FLOORPLANS";
export const SET_FLOORPLAN_ID = "SET_FLOORPLAN_ID";
export const SHOW_FLOOR_MENU = "SHOW_FLOOR_MENU";
export const SET_CURRENT_FLOOR_NUMBER = "SET_CURRENT_FLOOR_NUMBER";
export const SET_CURRENT_FLOOR_ID = "SET_CURRENT_FLOOR_ID"
export const SET_CONFIG_FLOORPLAN = "SET_CONFIG_FLOORPLAN";

export const GET_ORGANISATION = "GET_ORGANISATION";
export const GET_ORGANISATIONS = "GET_ORGANISATIONS";
export const GET_FAV_ORGANISATIONS = "GET_FAV_ORGANISATIONS";
export const ADD_ORGANISATION = "ADD_ORGANISATION";
export const UPDATE_ORGANISATION = "UPDATE_ORGANISATION";
export const SET_CURRENT_ORGANISATION = "SET_CURRENT_ORGANISATION";
export const CLEAR_ORGANISATION = "CLEAR_ORGANISATION";
export const DELETE_ORGANISATION = "DELETE_ORGANISATION";
export const ORGANISATION_ERROR = "ORGANISATION_ERROR";
export const FILTER_ORGANISATION = "FILTER_ORGANISATION";

export const GET_ITEM = "GET_ITEM";
export const GET_ITEMS = "GET_ITEMS";
export const GET_FAV_ITEMS = "GET_FAV_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const CLEAR_ITEM = "CLEAR_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEM_ERROR = "ITEM_ERROR";
export const FILTER_ITEM = "FILTER_ITEM";

export const GET_LINKED_TAG = "GET_LINKED_TAG";
export const GET_LINKED_TAGS = "GET_LINKED_TAGS";
export const GET_FAV_LINKED_TAGS = "GET_FAV_LINKED_TAGS";
export const ADD_LINKED_TAG = "ADD_LINKED_TAG";
export const UPDATE_LINKED_TAG = "UPDATE_LINKED_TAG";
export const SET_CURRENT_LINKED_TAG = "SET_CURRENT_LINKED_TAG";
export const CLEAR_LINKED_TAG = "CLEAR_LINKED_TAG";
export const DELETE_LINKED_TAG = "DELETE_LINKED_TAG";
export const LINKED_TAG_ERROR = "LINKED_TAG_ERROR";
export const FILTER_LINKED_TAG = "FILTER_LINKED_TAG";

export const GET_LINKED_TAG_INFO ="GET_LINKED_TAG_INFO"
export const HIDE_CARD = "HIDE_CARD";


export const GET_TAG_POSES = "GET_TAG_POSES";
export const TAG_POS_ERROR = "TAG_POS_ERROR";

export const SET_GEOFENCE_CREATE_STATUS = "SET_GEOFENCE_CREATE_STATUS"
export const GET_GEOFENCE = "GET_GEOFENCE";
export const GET_GEOFENCES = "GET_GEOFENCES";
export const GET_FAV_GEOFENCES = "GET_FAV_GEOFENCES";
export const ADD_GEOFENCE = "ADD_GEOFENCE";
export const UPDATE_GEOFENCE = "UPDATE_GEOFENCE";
export const SET_CURRENT_GEOFENCE = "SET_CURRENT_GEOFENCE";
export const CLEAR_GEOFENCE = "CLEAR_GEOFENCE";
export const DELETE_GEOFENCE = "DELETE_GEOFENCE";
export const GEOFENCE_ERROR = "GEOFENCE_ERROR";
export const FILTER_GEOFENCE = "FILTER_GEOFENCE";
export const GET_GEOFENCE_OF_FLOOR ="GET_GEOFENCE_OF_FLOOR";
export const SHOW_GEOFENCE_CARD = "SHOW_GEOFENCE_CARD";
export const HIDE_GEOFENCE_CARD="HIDE_GEOFENCE_CARD";
export const SET_NUMBER_OF_GEOFENCE = "SET_NUMBER_OF_GEOFENCE";

export const GET_TAGS_COUNT = "GET_TAGS_COUNT";
export const GET_GEOFENCES_COUNT = "GET_GEOFENCES_COUNT";
export const GET_BUILDINGS_COUNT = "GET_BUILDINGS_COUNT";
export const COUNT_ERROR = "COUNT_ERROR";


export const GET_GLTF = "GET_GLTF";
export const GET_GLTFS = "GET_GLTFS";
export const GET_FAV_GLTFS = "GET_FAV_GLTFS";
export const ADD_GLTF = "ADD_GLTF";
export const UPDATE_GLTF = "UPDATE_GLTF";
export const SET_CURRENT_GLTF = "SET_CURRENT_GLTF";
export const CLEAR_GLTF = "CLEAR_GLTF";
export const DELETE_GLTF = "DELETE_GLTF";
export const GLTF_ERROR = "GLTF_ERROR";
export const FILTER_GLTF = "FILTER_GLTF";
export const SET_GLTF_OF_FLOORPLAN = "SET_GLTF_OF_FLOORPLAN";
export const SET_GLTF_OF_FENCE_FLOORPLAN = "SET_GLTF_OF_FENCE_FLOORPLAN";
export const RESET_FLOOR_GLTF="RESET_FLOOR_GLTF"



export const SET_BACKDROP = "SET_BACKDROP"
export const GENERATE_API_KEY = "GENERATE_API_KEY"
export const DELETE_API_KEY = "DELETE_API_KEY"
export const GET_API_KEYS = "GET_API_KEYS"
export const TOKEN_GENERATED = "TOKEN_GENERATED"
export const RESET_TOKEN = "RESET_TOKEN"



export const SET_COLOR_INDEX = "SET_COLOR_INDEX"
 
